### ISSUE TITLE
Using remote server instead of bolt address

### ISSUE THREAD

**Issue by covid19uofa** [jackdbd/react-neovis-example#4]
When I'm trying to use a remote server address (*.databases.neo4j.io), I'm getting a WebSocket error and its failing to connect. Since the docs mentioned to connect using bolt:// address, is there any way to work around and use a remote server instead?

**Comment by jackdbd** [comment]
I'm not sure. Is this related to your issue?
https://neo4j.com/developer/kb/explanation-of-error-websocket-connection-failure/

**Comment by covid19uofa** [comment]
Ah, I'm not sure. using bolt:// actually worked. My problem is, since the DB is remote (*.databases.neo4j.io), its should be fetched by neo4j+s:// or bolt+s://. Thats how I did for flask and works fine. But when I use ""neovis.js/dist/neovis.js", I can only use bolt:// or neo4j:// and I have to give the configuration "ENCRYPTION_OFF:false" to make it work.
If I don't do that and give bolt+s://, I get this following error:
![image](https://user-images.githubusercontent.com/64765921/109412562-75301a80-79f4-11eb-959f-9a868e8b8fa0.png)

Any idea on fixing it? The problem with setting "encryption:false" and using bolt:// instead is that, when I deploy or use firefox for instance, there is a security error and the graph wont load:
![image](https://user-images.githubusercontent.com/64765921/109412638-e079ec80-79f4-11eb-9c94-976e2e4dcf83.png)

**Comment by covid19uofa** [comment]
@jackdbd  any idea? Sorry for the tag. I'm a bit stuck with this issue

**Comment by alinaqi12** [comment]
index.js:1 Neo4jError: Unknown Bolt protocol version: 0

    at neovis.js:1:1
    at new t (neovis.js:1:1)
    at t.value (neovis.js:53:1)
    at t.value (neovis.js:53:1)
    at t.value (neovis.js:55:1)
    at NeoGraph.js:35:1
    at commitHookEffectListMount (react-dom.development.js:19731:1)
    at commitPassiveHookEffects (react-dom.development.js:19769:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at flushPassiveEffectsImpl (react-dom.development.js:22853:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushPassiveEffects (react-dom.development.js:22820:1)
    at react-dom.development.js:22699:1
    at workLoop (scheduler.development.js:597:1)
    at flushWork (scheduler.development.js:552:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:164:1)
